// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	scanMachine: () => typedError<ScanResult, string>(__TAURI_INVOKE("scan_machine")),
	getSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_settings")),
	updateSettings: (settings: AppSettings) => typedError<AppSettings, string>(__TAURI_INVOKE("update_settings", { settings })),
	registerProject: (path: string) => typedError<AppSettings, string>(__TAURI_INVOKE("register_project", { path })),
	unregisterProject: (path: string) => typedError<AppSettings, string>(__TAURI_INVOKE("unregister_project", { path })),
	discoverProjects: (root: string) => typedError<string[], string>(__TAURI_INVOKE("discover_projects", { root })),
	/**
	 *  The full harness × kind capability matrix — the UI gates every action on
	 *  this, never on its own assumptions.
	 */
	capabilityTable: () => __TAURI_INVOKE<CapabilityRow[]>("capability_table"),
	/**
	 *  Where a problem report about this item belongs: the vstack upstream
	 *  (with a prefilled issue link) or the user's own repo.
	 */
	reportRoute: (scope: Scope, name: string, kind: "agent" | "skill" | "hook" | "command" | "mcp-server" | "plugin" | "pi-extension" | null) => typedError<ReportRouteView, string>(__TAURI_INVOKE("report_route", { scope, name, kind })),
	auditAll: () => typedError<AuditView_Serialize[], string>(__TAURI_INVOKE("audit_all")),
	applyPlan: (scope: Scope, removeOrphans: boolean, allowUnsafe: string[]) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("apply_plan", { scope, removeOrphans, allowUnsafe })),
	adoptItem: (scope: Scope, kind: ItemKind, name: string, harness: HarnessId) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("adopt_item", { scope, kind, name, harness })),
	toggleItem: (scope: Scope, kind: ItemKind, name: string, enabled: boolean) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("toggle_item", { scope, kind, name, enabled })),
	removeItem: (scope: Scope, kind: ItemKind, name: string) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("remove_item", { scope, kind, name })),
	/**
	 *  Every recorded decision across every scope, each read against what is
	 *  installed there now.
	 */
	listDecisions: () => typedError<DecisionsView_Serialize, string>(__TAURI_INVOKE("list_decisions")),
	/**
	 *  Dismiss the findings these tokens name, for one reason, in one scope.
	 *  The tokens are re-read against a fresh audit before anything is written;
	 *  one that no longer names what is installed stops the whole call.
	 */
	dismissFindings: (scope: Scope, tokens: string[], reason: DismissReason) => typedError<Dismissed_Serialize, string>(__TAURI_INVOKE("dismiss_findings", { scope, tokens, reason })),
	/**
	 *  Take a dismissal back. `dismissed_at` pins the exact record: a stale undo
	 *  finding a newer dismissal at the same key refuses rather than deleting
	 *  somebody's later decision.
	 */
	revokeDismissal: (scope: Scope, key: string, fingerprint: string, dismissedAt: string) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("revoke_dismissal", { scope, key, fingerprint, dismissedAt })),
	revokeSafetyOverride: (scope: Scope, key: string) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("revoke_safety_override", { scope, key })),
	getManifest: (scope: Scope) => typedError<{
	schema: number,
	sources?: { [key in string]: SourceDecl_Serialize },
	install: InstallDefaults,
	agents?: { [key in string]: ItemDecl_Serialize },
	skills?: { [key in string]: ItemDecl_Serialize },
	hooks?: { [key in string]: ItemDecl_Serialize },
	commands?: { [key in string]: ItemDecl_Serialize },
	"mcp-servers"?: { [key in string]: ItemDecl_Serialize },
	/**
	 *  Plugins are observe + enable/disable only; the key is
	 *  `name@marketplace`, provenance lives in the lock.
	 */
	plugins?: { [key in string]: PluginDecl },
	/**
	 *  Installed bundles: a curated set the catalog offers under one name.
	 *  What the set holds is the catalog's to say and derives on every plan;
	 *  this records only that the set is installed, and how its members
	 *  install — the same choices any declaration makes.
	 */
	bundles?: { [key in string]: ItemDecl_Serialize },
	"pi-extensions"?: { [key in string]: ItemDecl_Serialize },
	/**
	 *  Items the user removed and wants kept removed, by kind: a dependency
	 *  another item requires, or a member of an installed bundle. A refresh
	 *  honors these instead of re-deriving what was taken away, and the item
	 *  that wanted them says so in the audit.
	 */
	suppressed?: Partial<{ [key in ItemKind]: string[] }>,
	/**
	 *  Optional dependencies taken at install time, per item that offers
	 *  them. A choice, so it belongs here and survives refresh, cache loss,
	 *  and other machines; what those choices pull in does not.
	 */
	"optional-dependencies"?: { [key in string]: string[] },
	/**
	 *  Reviews of content the safety gate blocked, keyed by installation.
	 *  Each one binds to the content, the rule set and the findings it was
	 *  granted against, so it stops applying the moment any of them moves.
	 */
	"safety-overrides"?: { [key in string]: SafetyOverride_Serialize },
	/**
	 *  Findings judged not to be problems, keyed by installation, one
	 *  snapshot of the reviewed content per installation with each
	 *  dismissal beneath it. A dismissal settles a question and never
	 *  unblocks anything.
	 */
	"safety-reviews"?: { [key in string]: SafetyReview_Serialize },
	"agent-skills"?: { [key in string]: string[] },
	"agent-launch-instructions"?: { [key in string]: string },
	"agent-additional-instructions"?: { [key in string]: string },
	"skill-instructions"?: { [key in string]: string },
	/**  `[agent-frontmatter.<harness>.<agent>]`. */
	"agent-frontmatter"?: { [key in string]: { [key in string]: FrontmatterOverrides_Serialize } },
	"custom-hooks"?: CustomHook_Serialize[],
	"project-skills-dir"?: string | null,
	/**
	 *  Forked items by kind and name — `[forks.skill.<name>]`. The name is
	 *  the item's installed name, unchanged by forking.
	 */
	forks?: Partial<{ [key in ItemKind]: { [key in string]: ForkProvenance_Serialize } }>,
} | null, string>(__TAURI_INVOKE("get_manifest", { scope })),
	/**  Write an edited manifest and reconcile the scope to it. */
	updateManifest: (scope: Scope, manifest: Manifest_Deserialize) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("update_manifest", { scope, manifest })),
	editorInventory: (scope: Scope) => typedError<EditorInventory, string>(__TAURI_INVOKE("editor_inventory", { scope })),
	/**
	 *  The primary file behind one installed item, for the Library preview
	 *  pane — SKILL.md for a skill, the document itself for everything else
	 *  that has its own file.
	 */
	itemSource: (scope: Scope, kind: ItemKind, name: string, harness: HarnessId) => typedError<ItemSource, string>(__TAURI_INVOKE("item_source", { scope, kind, name, harness })),
	/**
	 *  Native folder picker. Blocking, so this must not run on the main thread
	 *  — an async command already runs off it, which is what the plugin's own
	 *  docs call for.
	 */
	pickFolder: () => typedError<string | null, string>(__TAURI_INVOKE("pick_folder")),
	/**
	 *  Shows `path` in the system file browser. Only ever reveals a path that
	 *  is actually there — the plain-word error is the fix, not a stack trace
	 *  from the OS call that would have failed instead.
	 */
	revealPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_path", { path })),
	/**
	 *  Opens `path` (file or directory — every candidate editor accepts both)
	 *  in the user's code editor. Not routed through `process::Hardened`: that
	 *  constructor hardens tool invocations core makes with captured output
	 *  and a timeout, but this is an app-shell concern with a different shape
	 *  — no shell, nothing to capture, and no timeout, because the editor is
	 *  the user's own long-lived GUI app and is meant to outlive us.
	 */
	openInEditor: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_in_editor", { path })),
	/**  Every declared source in every scope — the Sources page's one query. */
	sourcesOverview: () => typedError<SourceRow[], string>(__TAURI_INVOKE("sources_overview")),
	sourceAdd: (scope: Scope, name: string, reference: string) => typedError<SourceRow[], string>(__TAURI_INVOKE("source_add", { scope, name, reference })),
	sourceRemove: (scope: Scope, name: string) => typedError<SourceRow[], string>(__TAURI_INVOKE("source_remove", { scope, name })),
	sourceToggle: (scope: Scope, name: string, enabled: boolean) => typedError<SourceRow[], string>(__TAURI_INVOKE("source_toggle", { scope, name, enabled })),
	/**
	 *  Re-resolve every enabled remote across every scope. Returns warnings
	 *  (offline caches keep serving); hard failures surface as the error.
	 */
	sourcesRefresh: () => typedError<string[], string>(__TAURI_INVOKE("sources_refresh")),
	/**
	 *  Every curated set every catalog offers, across every scope — what the
	 *  Catalogs page lists under each source.
	 */
	bundlesOverview: () => typedError<BundleRow[], string>(__TAURI_INVOKE("bundles_overview")),
	/**
	 *  Install a set whole. Its members derive from the catalog, so this declares
	 *  one name and applies the plan that follows from it.
	 */
	bundleInstall: (scope: Scope, source: string, name: string, hold: boolean) => typedError<BundleRow[], string>(__TAURI_INVOKE("bundle_install", { scope, source, name, hold })),
	packageVersions: (scope: Scope, kind: ItemKind, name: string) => typedError<VersionRow[], string>(__TAURI_INVOKE("package_versions", { scope, kind, name })),
	/**
	 *  Every scope's update standing in one query — the sidebar badge, the
	 *  Updates page, and the Library's fork/edited flags all read this.
	 */
	updatesOverview: () => typedError<UpdateRow[], string>(__TAURI_INVOKE("updates_overview")),
	/**
	 *  Fetch every source's mirror — pinned ones included, that is the point —
	 *  then answer with the fresh standing. Fetch problems degrade to
	 *  warnings; a check for updates is never worth an error dialog.
	 */
	updatesRefresh: () => typedError<UpdateRow[], string>(__TAURI_INVOKE("updates_refresh")),
	updateSetIgnored: (scope: Scope, kind: ItemKind, name: string, repo: string, ignored: boolean) => typedError<UpdateRow[], string>(__TAURI_INVOKE("update_set_ignored", { scope, kind, name, repo, ignored })),
	/**
	 *  Hold a package at a version (or let it follow again) and apply the
	 *  change. The plan is whole-scope, like every apply: packages that follow
	 *  their source come current in the same pass, which is what following
	 *  means.
	 */
	packageSetRev: (scope: Scope, kind: ItemKind, name: string, rev: string | null) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("package_set_rev", { scope, kind, name, rev })),
	packageDiff: (scope: Scope, kind: ItemKind, name: string, from: VersionSel, to: VersionSel, harness: "claude" | "codex" | "opencode" | "cursor" | "pi" | "gemini" | "copilot" | null) => typedError<PackageDiff, string>(__TAURI_INVOKE("package_diff", { scope, kind, name, from, to, harness })),
	/**  Keep an edited install as a local fork, then render it in place. */
	packageFork: (scope: Scope, kind: ItemKind, name: string, harness: HarnessId) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("package_fork", { scope, kind, name, harness })),
	forkRename: (scope: Scope, kind: ItemKind, oldName: string, newName: string) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("fork_rename", { scope, kind, oldName, newName })),
	/**
	 *  Apply a scope with one package's edits discarded — the door back to
	 *  "the catalog's version wins", scoped to the package the user named so
	 *  a neighbour's edits are never taken along.
	 */
	applyDiscardEdits: (scope: Scope, kind: ItemKind, name: string) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("apply_discard_edits", { scope, kind, name })),
	packageFiles: (scope: Scope, kind: ItemKind, name: string) => typedError<PackageFile[], string>(__TAURI_INVOKE("package_files", { scope, kind, name })),
	packageFile: (scope: Scope, kind: ItemKind, name: string, path: string) => typedError<ItemSource, string>(__TAURI_INVOKE("package_file", { scope, kind, name, path })),
	packageReadme: (scope: Scope, kind: ItemKind, name: string) => typedError<{
	path: string,
	content: string,
	truncated: boolean,
} | null, string>(__TAURI_INVOKE("package_readme", { scope, kind, name })),
	packageMeta: (scope: Scope, kind: ItemKind, name: string) => typedError<PackageMeta_Serialize, string>(__TAURI_INVOKE("package_meta", { scope, kind, name })),
	windowMinimize: () => typedError<null, string>(__TAURI_INVOKE("window_minimize")),
	windowToggleMaximize: () => typedError<null, string>(__TAURI_INVOKE("window_toggle_maximize")),
	windowClose: () => typedError<null, string>(__TAURI_INVOKE("window_close")),
};

/* Types */
export type AntiPattern = {
	flag: string,
	detail: string,
	remediation: string,
};

/**  App preferences and the project registry — one settings file, nothing else. */
export type AppSettings = {
	schema: number,
	projects?: string[],
	/**  Per-harness override of the global root directory, keyed by harness id. */
	"harness-roots"?: { [key in string]: string },
	appearance?: Appearance,
	/**
	 *  Where the safety score starts warning and stops installing. These
	 *  live here rather than in a manifest on purpose: a manifest travels
	 *  with the repository it describes, and a catalog able to lower the bar
	 *  it is measured against is not being measured.
	 */
	safety?: Thresholds,
	/**
	 *  Packages whose update notifications are off. Here rather than in a
	 *  manifest for the same reason as `safety`: a notification preference
	 *  committed to a shared repository would silence a whole team.
	 */
	"ignored-updates"?: IgnoredUpdate[],
};

export type Appearance = "system" | "light" | "dark";

/**
 *  What the Audit page renders: drift rows plus the human-readable plan
 *  that would fix them.
 */
export type AuditView = AuditView_Serialize | AuditView_Deserialize;

/**
 *  What the Audit page renders: drift rows plus the human-readable plan
 *  that would fix them.
 */
export type AuditView_Deserialize = {
	scope: Scope,
	drift: DriftRow_Deserialize[],
	plan: string[],
	notes: string[],
	warnings: ItemWarning_Deserialize[],
	/**
	 *  What the safety rules found in the content installed here. Each row
	 *  carries two scores that are never combined: safety, which can hold an
	 *  install back, and quality, which only ever informs.
	 */
	safety: ItemSafety_Deserialize[],
	/**
	 *  Installations the plan would write but the safety gate holds back.
	 *  Kept apart from `safety` (which scores what is on disk) because the
	 *  two describe different bytes: an accept has to name the hash of what
	 *  apply would write, and only these rows carry it.
	 */
	heldBack: ItemSafety_Deserialize[],
	/**
	 *  Set when this one scope couldn't be read at all — a corrupt or
	 *  future-version lock or manifest. Carried as data so one scope's
	 *  failure never blanks every other scope's audit (drift/plan/notes/
	 *  warnings/safety are empty alongside it).
	 */
	error: ScopeError | null,
};

/**
 *  What the Audit page renders: drift rows plus the human-readable plan
 *  that would fix them.
 */
export type AuditView_Serialize = {
	scope: Scope,
	drift: DriftRow_Serialize[],
	plan: string[],
	notes: string[],
	warnings: ItemWarning_Serialize[],
	/**
	 *  What the safety rules found in the content installed here. Each row
	 *  carries two scores that are never combined: safety, which can hold an
	 *  install back, and quality, which only ever informs.
	 */
	safety: ItemSafety_Serialize[],
	/**
	 *  Installations the plan would write but the safety gate holds back.
	 *  Kept apart from `safety` (which scores what is on disk) because the
	 *  two describe different bytes: an accept has to name the hash of what
	 *  apply would write, and only these rows carry it.
	 */
	heldBack: ItemSafety_Serialize[],
	/**
	 *  Set when this one scope couldn't be read at all — a corrupt or
	 *  future-version lock or manifest. Carried as data so one scope's
	 *  failure never blanks every other scope's audit (drift/plan/notes/
	 *  warnings/safety are empty alongside it).
	 */
	error?: ScopeError | null,
};

/**  One curated set a catalog offers, as the Catalogs page lists it. */
export type BundleRow = {
	scope: Scope,
	source: string,
	name: string,
	description: string | null,
	version: string | null,
	category: string | null,
	/**  What it carries, each as the kind and name it installs under. */
	members: string[],
	installed: boolean,
};

export type CapabilityRow = {
	harness: HarnessId,
	kind: ItemKind,
	caps: KindCaps,
};

/**
 *  The catalog's own claims about the plugin an item ships in — read-side
 *  display only, never intent.
 */
export type CatalogGroupMeta = {
	version: string | null,
	description: string | null,
	author: string | null,
	license: string | null,
	homepage: string | null,
	category: string | null,
};

export type CustomHook = CustomHook_Serialize | CustomHook_Deserialize;

export type CustomHook_Deserialize = {
	event: string,
	matcher: string | null,
	command: string,
	description: string | null,
	agents?: HookAgents,
};

export type CustomHook_Serialize = {
	event: string,
	matcher?: string | null,
	command: string,
	description?: string | null,
	agents: HookAgents,
};

/**  What one record decided. */
export type DecisionRecord = DecisionRecord_Serialize | DecisionRecord_Deserialize;

/**  What one record decided. */
export type DecisionRecord_Deserialize = 
/**  A whole item's findings, read and accepted. */
({ kind: "accepted"; findings: number; grantedAt: string }) & { dismissedAt?: never; finding?: never; fingerprint?: never; reason?: never } | 
/**
 *  One finding, judged not to be a problem. `finding` is the current
 *  text of what it dismissed, present while that finding is still there.
 */
({ kind: "dismissed"; fingerprint: string; reason: DismissReason; dismissedAt: string; finding: Finding | null }) & { findings?: never; grantedAt?: never };

/**  What one record decided. */
export type DecisionRecord_Serialize = 
/**  A whole item's findings, read and accepted. */
({ kind: "accepted"; findings: number; grantedAt: string }) & { dismissedAt?: never; finding?: never; fingerprint?: never; reason?: never } | 
/**
 *  One finding, judged not to be a problem. `finding` is the current
 *  text of what it dismissed, present while that finding is still there.
 */
({ kind: "dismissed"; fingerprint: string; reason: DismissReason; dismissedAt: string; finding?: Finding | null }) & { findings?: never; grantedAt?: never };

/**
 *  What is recorded about one finding, read against the content in front
 *  of us now.
 */
export type DecisionState = DecisionState_Serialize | DecisionState_Deserialize;

/**
 *  What is recorded about one finding, read against the content in front
 *  of us now.
 */
export type DecisionState_Deserialize = 
/**
 *  Nobody has ruled on this finding for this content. `earlier` says why
 *  a previous ruling no longer applies, when there was one.
 */
({ state: "open"; earlier: string | null }) & { dismissedAt?: never; grantedAt?: never; reason?: never } | 
/**  Judged not to be a problem, for exactly this content. */
({ state: "dismissed"; reason: DismissReason; dismissedAt: string }) & { earlier?: never; grantedAt?: never } | 
/**
 *  Covered by an acceptance of the whole item: every finding on it was
 *  read and the item installed anyway.
 */
({ state: "accepted"; grantedAt: string }) & { dismissedAt?: never; earlier?: never; reason?: never };

/**
 *  What is recorded about one finding, read against the content in front
 *  of us now.
 */
export type DecisionState_Serialize = 
/**
 *  Nobody has ruled on this finding for this content. `earlier` says why
 *  a previous ruling no longer applies, when there was one.
 */
({ state: "open"; earlier?: string | null }) & { dismissedAt?: never; grantedAt?: never; reason?: never } | 
/**  Judged not to be a problem, for exactly this content. */
({ state: "dismissed"; reason: DismissReason; dismissedAt: string }) & { earlier?: never; grantedAt?: never } | 
/**
 *  Covered by an acceptance of the whole item: every finding on it was
 *  read and the item installed anyway.
 */
({ state: "accepted"; grantedAt: string }) & { dismissedAt?: never; earlier?: never; reason?: never };

/**
 *  A scope whose decisions could not be read, carried as data beside the
 *  ones that could. A view promising every decision must say which
 *  scopes it is not speaking for, never silently skip them.
 */
export type DecisionsScopeError = {
	scope: Scope,
	error: ScopeError,
};

export type DecisionsView = DecisionsView_Serialize | DecisionsView_Deserialize;

export type DecisionsView_Deserialize = {
	decisions: RecordedDecision_Deserialize[],
	errors: DecisionsScopeError[],
};

export type DecisionsView_Serialize = {
	decisions: RecordedDecision_Serialize[],
	errors: DecisionsScopeError[],
};

/**  One rule firing once, and what it cost. */
export type Deduction = {
	rule: string,
	location: string,
	severity: Severity,
	points: number,
	/**  A later hit from a rule that has already been counted in full. */
	repeat: boolean,
};

/**  A harness found on this machine. */
export type DetectedHarness = {
	harness: HarnessId,
	/**  The directory whose existence marks the harness as installed. */
	root: string,
	version: string | null,
};

export type DimensionScore = {
	dimension: string,
	weightPercent: number,
	scorePercent: number,
};

/**
 *  Why a finding was dismissed. Every reason is a claim about the content
 *  — a project's dismissals travel with the repository, so a reason must
 *  mean the same thing to whoever reads it next, and none of them may be
 *  one person's tolerance for risk.
 */
export type DismissReason = 
/**  The rule misread this: nothing here does what the finding says. */
"wrong-call" | 
/**  The flagged behaviour is what this item is for. */
"intended" | 
/**
 *  The content is from a source the reviewer trusts. Bound to that
 *  source's identity: the same bytes from somewhere else are a
 *  different question.
 */
"trusted-source";

/**
 *  One dismissed finding, keyed in its snapshot by the finding's
 *  fingerprint.
 */
export type Dismissal = Dismissal_Serialize | Dismissal_Deserialize;

/**
 *  One dismissed finding, keyed in its snapshot by the finding's
 *  fingerprint.
 */
export type Dismissal_Deserialize = {
	reason: DismissReason,
	"dismissed-at": string,
	/**
	 *  The source identity a `TrustedSource` dismissal trusted — the
	 *  resolved provenance the lock records, or the git origin of an
	 *  unmanaged item's files. Absent for the other reasons.
	 */
	source?: string | null,
};

/**
 *  One dismissed finding, keyed in its snapshot by the finding's
 *  fingerprint.
 */
export type Dismissal_Serialize = {
	reason: DismissReason,
	"dismissed-at": string,
	/**
	 *  The source identity a `TrustedSource` dismissal trusted — the
	 *  resolved provenance the lock records, or the git origin of an
	 *  unmanaged item's files. Absent for the other reasons.
	 */
	source?: string | null,
};

/**
 *  What a dismissal came back with: the scope's fresh view, and exactly
 *  what was written.
 */
export type Dismissed = Dismissed_Serialize | Dismissed_Deserialize;

/**
 *  One record a dismissal wrote, as an undo names it: the same key and
 *  fingerprint the registry uses, and the timestamp that pins this exact
 *  record so an old undo cannot delete a newer decision at the same key.
 */
export type DismissedRecord = {
	key: string,
	fingerprint: string,
	dismissedAt: string,
};

/**
 *  What a dismissal came back with: the scope's fresh view, and exactly
 *  what was written.
 */
export type Dismissed_Deserialize = {
	view: AuditView_Deserialize,
	records: DismissedRecord[],
};

/**
 *  What a dismissal came back with: the scope's fresh view, and exactly
 *  what was written.
 */
export type Dismissed_Serialize = {
	view: AuditView_Serialize,
	records: DismissedRecord[],
};

/**
 *  Why an installation diverged, when the plan can tell. `LocalEdit` and
 *  `Both` are the causes that block writes: the user's bytes are on disk
 *  and only an explicit choice may take them.
 */
export type DriftCause = "upstream-changed" | "local-edit" | "both";

export type DriftRow = DriftRow_Serialize | DriftRow_Deserialize;

export type DriftRow_Deserialize = {
	kind: ItemKind,
	name: string,
	harness: HarnessId,
	scope: Scope,
	state: DriftState,
	detail: string,
	cause?: DriftCause | null,
};

export type DriftRow_Serialize = {
	kind: ItemKind,
	name: string,
	harness: HarnessId,
	scope: Scope,
	state: DriftState,
	detail: string,
	cause?: DriftCause | null,
};

export type DriftState = 
/**  Declared but not on disk (or never recorded). */
"missing" | 
/**  On disk but no longer matching declaration + source. */
"stale" | 
/**  Recorded in the lock but no longer declared. */
"orphaned" | 
/**  On disk in a managed surface, but not ours. */
"unmanaged" | 
/**  Needs a human: foreign symlink, occupied target, or provenance clash. */
"conflict";

/**
 *  What the Customize page needs to offer real choices: the names already
 *  declared here plus the skills any ready source can supply.
 */
export type EditorInventory = {
	declaredAgents: string[],
	declaredSkills: string[],
	availableSkills: string[],
	harnesses: HarnessId[],
};

/**
 *  Whether the harness runs what vstack writes, or only reads it as prose.
 *  `managed` says vstack can write and track an artifact; it never said the
 *  tool would act on it, and a safety hook must not read as protection on a
 *  tool that can merely suggest it.
 */
export type Enforcement = 
/**  The harness executes the command and honors its result. */
"enforced" | 
/**  Rendered as instructions the model is free to ignore. */
"advisory" | 
/**
 *  Nothing here executes: every kind but Hook, and the harnesses vstack
 *  declares no hook surface for.
 */
"not-applicable";

export type FileDiff = {
	/**  Forward-slash relative path, whatever the platform. */
	path: string,
	status: FileStatus,
	additions: number,
	deletions: number,
	/**  One side was not valid UTF-8 and is shown lossily. */
	lossy: boolean,
	hunks: Hunk[],
};

/**
 *  How an observed item exists on disk. Kinds that live as entries inside a
 *  shared config file (MCP servers, some hooks) are `ConfigEntry`.
 */
export type FileState = { state: "file" } | { state: "dir" } | { state: "symlink"; target: string; broken: boolean } | { state: "config-entry" };

export type FileStatus = "added" | "removed" | "modified" | 
/**  Holds a NUL byte on either side — compared, never rendered as text. */
"binary" | 
/**  Past the size or line budget — reported, not diffed. */
"too-large";

/**
 *  One safety problem, where it is, and what to do about it. The message
 *  never holds a matched secret — only its fingerprint (invariant of
 *  `secret::fingerprint_secret`).
 */
export type Finding = {
	rule: string,
	severity: Severity,
	/**  The file and line, or the config key that holds the entry. */
	location: string,
	message: string,
	remediation: string,
};

/**
 *  One finding as a thing a person can rule on. Sits beside the finding it
 *  is about — `ItemSafety.decisions[i]` speaks for `ItemSafety.findings[i]`.
 */
export type FindingDecision = FindingDecision_Serialize | FindingDecision_Deserialize;

/**
 *  One finding as a thing a person can rule on. Sits beside the finding it
 *  is about — `ItemSafety.decisions[i]` speaks for `ItemSafety.findings[i]`.
 */
export type FindingDecision_Deserialize = {
	/**
	 *  This finding's identity within its item — what a recorded decision
	 *  is keyed by, and what tells one occurrence of a finding from another
	 *  when the same bytes are read through several tools.
	 */
	fingerprint: string,
	/**
	 *  Names exactly this finding on exactly this content. Opaque to the
	 *  UI; the only thing a dismiss command accepts. Absent where the
	 *  content cannot be read here — there is nothing exact to bind a
	 *  decision to, so none can be made.
	 */
	token: string | null,
	state: DecisionState_Deserialize,
};

/**
 *  One finding as a thing a person can rule on. Sits beside the finding it
 *  is about — `ItemSafety.decisions[i]` speaks for `ItemSafety.findings[i]`.
 */
export type FindingDecision_Serialize = {
	/**
	 *  This finding's identity within its item — what a recorded decision
	 *  is keyed by, and what tells one occurrence of a finding from another
	 *  when the same bytes are read through several tools.
	 */
	fingerprint: string,
	/**
	 *  Names exactly this finding on exactly this content. Opaque to the
	 *  UI; the only thing a dismiss command accepts. Absent where the
	 *  content cannot be read here — there is nothing exact to bind a
	 *  decision to, so none can be made.
	 */
	token: string | null,
	state: DecisionState_Serialize,
};

/**
 *  Where a fork came from. A fork keeps the item's installed name — the
 *  declaration just switches to the local source, so nothing that depends
 *  on the name breaks — and this records what it replaced. Manifest, not
 *  lock, because the package page keeps reading it after any cache loss.
 */
export type ForkProvenance = ForkProvenance_Serialize | ForkProvenance_Deserialize;

/**
 *  Where a fork came from. A fork keeps the item's installed name — the
 *  declaration just switches to the local source, so nothing that depends
 *  on the name breaks — and this records what it replaced. Manifest, not
 *  lock, because the package page keeps reading it after any cache loss.
 */
export type ForkProvenance_Deserialize = {
	/**  Declared source name the original installed from. */
	source: string,
	repo?: string | null,
	/**  The source commit the edited install was based on, when known. */
	commit?: string | null,
	"forked-at": string,
};

/**
 *  Where a fork came from. A fork keeps the item's installed name — the
 *  declaration just switches to the local source, so nothing that depends
 *  on the name breaks — and this records what it replaced. Manifest, not
 *  lock, because the package page keeps reading it after any cache loss.
 */
export type ForkProvenance_Serialize = {
	/**  Declared source name the original installed from. */
	source: string,
	repo?: string | null,
	/**  The source commit the edited install was based on, when known. */
	commit?: string | null,
	"forked-at": string,
};

/**  Typed `[agent-frontmatter.<harness>.<agent>]` overrides — v1's field set. */
export type FrontmatterOverrides = FrontmatterOverrides_Serialize | FrontmatterOverrides_Deserialize;

/**  Typed `[agent-frontmatter.<harness>.<agent>]` overrides — v1's field set. */
export type FrontmatterOverrides_Deserialize = {
	color: string | null,
	model: string | null,
	"deny-tools": string[] | null,
	/**
	 *  Allow-only tool intent: replaces a source-side `tools:` allowlist for
	 *  this harness. Distinct from `deny_tools`, which only narrows.
	 */
	"allow-tools": string[] | null,
	"allowed-subagents": string[] | null,
	pane: boolean | null,
	background: boolean | null,
	effort: string | null,
	isolation: string | null,
	memory: string | null,
	mode: string | null,
	"sandbox-mode": string | null,
	"model-reasoning-effort": string | null,
	"nickname-candidates": string[] | null,
};

/**  Typed `[agent-frontmatter.<harness>.<agent>]` overrides — v1's field set. */
export type FrontmatterOverrides_Serialize = {
	color?: string | null,
	model?: string | null,
	"deny-tools"?: string[] | null,
	/**
	 *  Allow-only tool intent: replaces a source-side `tools:` allowlist for
	 *  this harness. Distinct from `deny_tools`, which only narrows.
	 */
	"allow-tools"?: string[] | null,
	"allowed-subagents"?: string[] | null,
	pane?: boolean | null,
	background?: boolean | null,
	effort?: string | null,
	isolation?: string | null,
	memory?: string | null,
	mode?: string | null,
	"sandbox-mode"?: string | null,
	"model-reasoning-effort"?: string | null,
	"nickname-candidates"?: string[] | null,
};

export type HarnessId = "claude" | "codex" | "opencode" | "cursor" | "pi" | "gemini" | "copilot";

export type HookAgents = 
/**  `"all"`, a role name, or a single agent name. */
string | string[];

export type Hunk = {
	header: string,
	lines: Line[],
};

/**
 *  A package whose update notifications are switched off, by everything
 *  that identifies it: an ignore for one project's `gh` skill from one
 *  repository must not silence another project's unrelated `gh`.
 */
export type IgnoredUpdate = {
	/**  `"global"` or the project root path. */
	scope: string,
	kind: ItemKind,
	name: string,
	repo: string,
};

export type InstallDefaults = {
	harnesses?: HarnessId[],
	method?: Method,
};

/**  One declared item: `[agents.<name>]` / `[skills.<name>]`. */
export type ItemDecl = ItemDecl_Serialize | ItemDecl_Deserialize;

/**  One declared item: `[agents.<name>]` / `[skills.<name>]`. */
export type ItemDecl_Deserialize = {
	source: string,
	harnesses: HarnessId[] | null,
	method: Method | null,
	/**
	 *  Which revision of the source this item reads, outranking the
	 *  source-level `rev`. Same semantics: a full commit id pins, a tag or
	 *  branch tracks. Present means the item holds here while the source
	 *  moves — this is what "manual updates" is; absent means the item
	 *  follows the source.
	 */
	rev?: string | null,
	enabled?: boolean,
};

/**  One declared item: `[agents.<name>]` / `[skills.<name>]`. */
export type ItemDecl_Serialize = {
	source: string,
	harnesses?: HarnessId[] | null,
	method?: Method | null,
	/**
	 *  Which revision of the source this item reads, outranking the
	 *  source-level `rev`. Same semantics: a full commit id pins, a tag or
	 *  branch tracks. Present means the item holds here while the source
	 *  moves — this is what "manual updates" is; absent means the item
	 *  follows the source.
	 */
	rev?: string | null,
	enabled: boolean,
};

export type ItemKind = "agent" | "skill" | "hook" | "command" | "mcp-server" | "plugin" | "pi-extension";

/**
 *  One installation's two scores and everything behind them. Safety and
 *  quality sit side by side and are never combined: one answers whether the
 *  content is dangerous, the other whether it is any good, and averaging
 *  them would let a well-written attack outscore a clumsy honest skill.
 */
export type ItemSafety = ItemSafety_Serialize | ItemSafety_Deserialize;

/**
 *  One installation's two scores and everything behind them. Safety and
 *  quality sit side by side and are never combined: one answers whether the
 *  content is dangerous, the other whether it is any good, and averaging
 *  them would let a well-written attack outscore a clumsy honest skill.
 */
export type ItemSafety_Deserialize = {
	kind: ItemKind,
	name: string,
	harness: HarnessId,
	scope: Scope,
	/**
	 *  The artifact's path, or the config file holding the entry — what
	 *  every finding's location is relative to.
	 */
	location: string,
	safety: SafetyScore,
	/**  Advisory only, and absent for kinds with no authored prose. */
	quality: QualityScore | null,
	findings: Finding[],
	/**  Rules that apply to this kind but had no bytes to read here. */
	skipped: SkippedRule[],
	verdict: Verdict,
	/**  Why the verdict is what it is, in sentences. */
	reasons: string[],
	/**
	 *  The identity of the bytes the rules read — the reduced input the
	 *  findings came out of, budgets and lossy decoding included.
	 */
	contentHash: string,
	/**
	 *  The identity of the complete bytes, or of the exact config entry. A
	 *  decision binds to this and the flag that grants one carries it, so it
	 *  is what a reviewer is accepting. `None` where the bytes cannot be
	 *  reached from here at all.
	 */
	reviewHash: string | null,
	/**
	 *  Where the bytes came from: the resolved provenance the lock records,
	 *  or the git origin of an unmanaged item's files. What a trusted-source
	 *  dismissal binds to. `None` where nothing on this machine says.
	 */
	provenance: string | null,
	override: OverrideState,
	/**  What has been decided about each finding, in the findings' order. */
	decisions: FindingDecision_Deserialize[],
};

/**
 *  One installation's two scores and everything behind them. Safety and
 *  quality sit side by side and are never combined: one answers whether the
 *  content is dangerous, the other whether it is any good, and averaging
 *  them would let a well-written attack outscore a clumsy honest skill.
 */
export type ItemSafety_Serialize = {
	kind: ItemKind,
	name: string,
	harness: HarnessId,
	scope: Scope,
	/**
	 *  The artifact's path, or the config file holding the entry — what
	 *  every finding's location is relative to.
	 */
	location: string,
	safety: SafetyScore,
	/**  Advisory only, and absent for kinds with no authored prose. */
	quality: QualityScore | null,
	findings: Finding[],
	/**  Rules that apply to this kind but had no bytes to read here. */
	skipped: SkippedRule[],
	verdict: Verdict,
	/**  Why the verdict is what it is, in sentences. */
	reasons: string[],
	/**
	 *  The identity of the bytes the rules read — the reduced input the
	 *  findings came out of, budgets and lossy decoding included.
	 */
	contentHash: string,
	/**
	 *  The identity of the complete bytes, or of the exact config entry. A
	 *  decision binds to this and the flag that grants one carries it, so it
	 *  is what a reviewer is accepting. `None` where the bytes cannot be
	 *  reached from here at all.
	 */
	reviewHash: string | null,
	/**
	 *  Where the bytes came from: the resolved provenance the lock records,
	 *  or the git origin of an unmanaged item's files. What a trusted-source
	 *  dismissal binds to. `None` where nothing on this machine says.
	 */
	provenance: string | null,
	override: OverrideState,
	/**  What has been decided about each finding, in the findings' order. */
	decisions: FindingDecision_Serialize[],
};

export type ItemSource = {
	path: string,
	content: string,
	truncated: boolean,
};

/**
 *  A per-item render or parse warning, with the fix when there is one —
 *  shown in plan previews, the CLI, and the Audit page.
 */
export type ItemWarning = ItemWarning_Serialize | ItemWarning_Deserialize;

/**
 *  A per-item render or parse warning, with the fix when there is one —
 *  shown in plan previews, the CLI, and the Audit page.
 */
export type ItemWarning_Deserialize = {
	kind: ItemKind,
	name: string,
	harness: HarnessId | null,
	message: string,
	remediation: string | null,
};

/**
 *  A per-item render or parse warning, with the fix when there is one —
 *  shown in plan previews, the CLI, and the Audit page.
 */
export type ItemWarning_Serialize = {
	kind: ItemKind,
	name: string,
	harness?: HarnessId | null,
	message: string,
	remediation?: string | null,
};

/**
 *  What each operation supports for one harness × kind. `observe` is derived
 *  from adapter surface declarations (tested); mutation columns land with
 *  their phases and stay honest through those phases' tests.
 */
export type KindCaps = {
	observe: OpSupport,
	adopt: OpSupport,
	install: OpSupport,
	toggle: OpSupport,
	remove: OpSupport,
	refresh: OpSupport,
	/**
	 *  The kind the harness actually stores this one as, when it has no
	 *  surface of its own to write to. `observe` keeps describing the
	 *  item's own surfaces; what a mutation writes is observable at the
	 *  emitted kind's, which is where the honesty check looks.
	 */
	installsAs: ItemKind | null,
	/**
	 *  Only Hook rows carry anything but `NotApplicable` — the axis exists
	 *  to separate a hook the tool runs from one it merely reads.
	 */
	enforcement: Enforcement,
};

export type Line = {
	kind: LineKind,
	text: string,
	oldNo: number | null,
	newNo: number | null,
};

export type LineKind = "context" | "add" | "remove";

export type Manifest = Manifest_Serialize | Manifest_Deserialize;

export type Manifest_Deserialize = {
	schema: number,
	sources?: { [key in string]: SourceDecl_Deserialize },
	install?: InstallDefaults,
	agents?: { [key in string]: ItemDecl_Deserialize },
	skills?: { [key in string]: ItemDecl_Deserialize },
	hooks?: { [key in string]: ItemDecl_Deserialize },
	commands?: { [key in string]: ItemDecl_Deserialize },
	"mcp-servers"?: { [key in string]: ItemDecl_Deserialize },
	/**
	 *  Plugins are observe + enable/disable only; the key is
	 *  `name@marketplace`, provenance lives in the lock.
	 */
	plugins?: { [key in string]: PluginDecl },
	/**
	 *  Installed bundles: a curated set the catalog offers under one name.
	 *  What the set holds is the catalog's to say and derives on every plan;
	 *  this records only that the set is installed, and how its members
	 *  install — the same choices any declaration makes.
	 */
	bundles?: { [key in string]: ItemDecl_Deserialize },
	"pi-extensions"?: { [key in string]: ItemDecl_Deserialize },
	/**
	 *  Items the user removed and wants kept removed, by kind: a dependency
	 *  another item requires, or a member of an installed bundle. A refresh
	 *  honors these instead of re-deriving what was taken away, and the item
	 *  that wanted them says so in the audit.
	 */
	suppressed?: Partial<{ [key in ItemKind]: string[] }>,
	/**
	 *  Optional dependencies taken at install time, per item that offers
	 *  them. A choice, so it belongs here and survives refresh, cache loss,
	 *  and other machines; what those choices pull in does not.
	 */
	"optional-dependencies"?: { [key in string]: string[] },
	/**
	 *  Reviews of content the safety gate blocked, keyed by installation.
	 *  Each one binds to the content, the rule set and the findings it was
	 *  granted against, so it stops applying the moment any of them moves.
	 */
	"safety-overrides"?: { [key in string]: SafetyOverride_Deserialize },
	/**
	 *  Findings judged not to be problems, keyed by installation, one
	 *  snapshot of the reviewed content per installation with each
	 *  dismissal beneath it. A dismissal settles a question and never
	 *  unblocks anything.
	 */
	"safety-reviews"?: { [key in string]: SafetyReview_Deserialize },
	"agent-skills"?: { [key in string]: string[] },
	"agent-launch-instructions"?: { [key in string]: string },
	"agent-additional-instructions"?: { [key in string]: string },
	"skill-instructions"?: { [key in string]: string },
	/**  `[agent-frontmatter.<harness>.<agent>]`. */
	"agent-frontmatter"?: { [key in string]: { [key in string]: FrontmatterOverrides_Deserialize } },
	"custom-hooks"?: CustomHook_Deserialize[],
	"project-skills-dir": string | null,
	/**
	 *  Forked items by kind and name — `[forks.skill.<name>]`. The name is
	 *  the item's installed name, unchanged by forking.
	 */
	forks?: Partial<{ [key in ItemKind]: { [key in string]: ForkProvenance_Deserialize } }>,
};

export type Manifest_Serialize = {
	schema: number,
	sources?: { [key in string]: SourceDecl_Serialize },
	install: InstallDefaults,
	agents?: { [key in string]: ItemDecl_Serialize },
	skills?: { [key in string]: ItemDecl_Serialize },
	hooks?: { [key in string]: ItemDecl_Serialize },
	commands?: { [key in string]: ItemDecl_Serialize },
	"mcp-servers"?: { [key in string]: ItemDecl_Serialize },
	/**
	 *  Plugins are observe + enable/disable only; the key is
	 *  `name@marketplace`, provenance lives in the lock.
	 */
	plugins?: { [key in string]: PluginDecl },
	/**
	 *  Installed bundles: a curated set the catalog offers under one name.
	 *  What the set holds is the catalog's to say and derives on every plan;
	 *  this records only that the set is installed, and how its members
	 *  install — the same choices any declaration makes.
	 */
	bundles?: { [key in string]: ItemDecl_Serialize },
	"pi-extensions"?: { [key in string]: ItemDecl_Serialize },
	/**
	 *  Items the user removed and wants kept removed, by kind: a dependency
	 *  another item requires, or a member of an installed bundle. A refresh
	 *  honors these instead of re-deriving what was taken away, and the item
	 *  that wanted them says so in the audit.
	 */
	suppressed?: Partial<{ [key in ItemKind]: string[] }>,
	/**
	 *  Optional dependencies taken at install time, per item that offers
	 *  them. A choice, so it belongs here and survives refresh, cache loss,
	 *  and other machines; what those choices pull in does not.
	 */
	"optional-dependencies"?: { [key in string]: string[] },
	/**
	 *  Reviews of content the safety gate blocked, keyed by installation.
	 *  Each one binds to the content, the rule set and the findings it was
	 *  granted against, so it stops applying the moment any of them moves.
	 */
	"safety-overrides"?: { [key in string]: SafetyOverride_Serialize },
	/**
	 *  Findings judged not to be problems, keyed by installation, one
	 *  snapshot of the reviewed content per installation with each
	 *  dismissal beneath it. A dismissal settles a question and never
	 *  unblocks anything.
	 */
	"safety-reviews"?: { [key in string]: SafetyReview_Serialize },
	"agent-skills"?: { [key in string]: string[] },
	"agent-launch-instructions"?: { [key in string]: string },
	"agent-additional-instructions"?: { [key in string]: string },
	"skill-instructions"?: { [key in string]: string },
	/**  `[agent-frontmatter.<harness>.<agent>]`. */
	"agent-frontmatter"?: { [key in string]: { [key in string]: FrontmatterOverrides_Serialize } },
	"custom-hooks"?: CustomHook_Serialize[],
	"project-skills-dir"?: string | null,
	/**
	 *  Forked items by kind and name — `[forks.skill.<name>]`. The name is
	 *  the item's installed name, unchanged by forking.
	 */
	forks?: Partial<{ [key in ItemKind]: { [key in string]: ForkProvenance_Serialize } }>,
};

export type Method = "symlink" | "copy";

/**
 *  One item as the scanner found it — read-only truth, no interpretation of
 *  whether it is declared or managed.
 */
export type ObservedItem = {
	kind: ItemKind,
	name: string,
	harness: HarnessId,
	scope: Scope,
	/**  Path of the artifact, or of the config file that contains the entry. */
	path: string,
	fileState: FileState,
	/**
	 *  Observable enabled/disabled state; `None` when the harness has no
	 *  observable toggle for this kind.
	 */
	enabled: boolean | null,
	/**  Best-effort provenance: git origin URL of the content's real location. */
	origin: string | null,
	description: string | null,
	/**
	 *  What this item says it is for. Empty when it says nothing — a tag is
	 *  something an author writes down, never something inferred from a
	 *  name, because a wrong guess is worse than no answer.
	 */
	tags: Tag[],
	/**
	 *  Unix seconds the primary file last changed, as `u32` because specta
	 *  refuses to export a 64-bit int (precision loss crossing the IPC
	 *  boundary) — good until year 2106. `None` where the item has no
	 *  single file of its own to stat (a config-entry kind, or a stat that
	 *  failed) — a shared file's mtime does not describe any one entry
	 *  inside it.
	 */
	modifiedAt: number | null,
};

export type OpSupport = {
	project: boolean,
	global: boolean,
};

/**  Whether a recorded override still speaks for what is in front of us. */
export type OverrideState = 
/**  Nothing recorded for this installation. */
{ state: "absent" } | 
/**  Recorded, and still describing exactly this. */
{ state: "active" } | 
/**  Recorded, but what it was granted against has changed since. */
{ state: "stale"; why: string };

export type PackageDiff = {
	files: FileDiff[],
	totalAdditions: number,
	totalDeletions: number,
	/**  The comparison hit a budget; what is shown is a prefix, not the whole. */
	truncated: boolean,
};

/**
 *  One file inside the package, path relative to the package root with
 *  forward slashes whatever the platform.
 */
export type PackageFile = {
	path: string,
	size: number,
	isReadme: boolean,
};

export type PackageMeta = PackageMeta_Serialize | PackageMeta_Deserialize;

export type PackageMeta_Deserialize = {
	source: string,
	/**  `owner/repo`, when the source is remote. */
	repo: string | null,
	/**  A safe https link to the repository, when one can be formed. */
	repoUrl: string | null,
	/**  The declaration's hold, when it has one. */
	rev: string | null,
	/**  The content revision installed now. */
	current: VersionRef | null,
	installedAt: string | null,
	harnesses: HarnessId[],
	enabled: boolean,
	fork: ForkProvenance_Deserialize | null,
	catalog: CatalogGroupMeta | null,
};

export type PackageMeta_Serialize = {
	source: string,
	/**  `owner/repo`, when the source is remote. */
	repo: string | null,
	/**  A safe https link to the repository, when one can be formed. */
	repoUrl: string | null,
	/**  The declaration's hold, when it has one. */
	rev: string | null,
	/**  The content revision installed now. */
	current: VersionRef | null,
	installedAt: string | null,
	harnesses: HarnessId[],
	enabled: boolean,
	fork: ForkProvenance_Serialize | null,
	catalog: CatalogGroupMeta | null,
};

/**
 *  One declared plugin. The harness is part of the declaration because more
 *  than one tool reads an `enabledPlugins` map of its own: without it, a
 *  plugin meant for one tool would be switched on in every tool's settings,
 *  which is a claim about software the user never installed there.
 * 
 *  A declaration written before the harness was part of it belongs to Claude
 *  Code — the only tool whose plugin switch vstack ever wrote — so that is
 *  what an older manifest reads back as, and the next write records it.
 */
export type PluginDecl = {
	enabled?: boolean,
	harness?: HarnessId,
};

export type QualityScore = {
	score: number,
	dimensions: DimensionScore[],
	antiPatterns: AntiPattern[],
	/**
	 *  What the anti-patterns multiplied the weighted total by, as a
	 *  percentage. Floors at 50 — the penalty shapes a score, it does not
	 *  replace it.
	 */
	penaltyPercent: number,
};

/**  Whether a recorded decision still speaks for anything. */
export type RecordState = 
/**  Describing exactly what is installed now. */
{ state: "active" } | 
/**  Recorded, but what it was made against has changed since. */
{ state: "stale"; why: string } | 
/**  The item it was about is no longer installed here. */
{ state: "obsolete" };

/**
 *  One recorded decision, as the registry lists it. `key` is the manifest's
 *  own spelling and is what revoke takes back, so even an entry a hand edit
 *  mangled can still be withdrawn; the typed fields are parsed from it for
 *  display and absent where it does not parse.
 */
export type RecordedDecision = RecordedDecision_Serialize | RecordedDecision_Deserialize;

/**
 *  One recorded decision, as the registry lists it. `key` is the manifest's
 *  own spelling and is what revoke takes back, so even an entry a hand edit
 *  mangled can still be withdrawn; the typed fields are parsed from it for
 *  display and absent where it does not parse.
 */
export type RecordedDecision_Deserialize = {
	scope: Scope,
	key: string,
	kind: ItemKind | null,
	name: string,
	harness: HarnessId | null,
	record: DecisionRecord_Deserialize,
	state: RecordState,
};

/**
 *  One recorded decision, as the registry lists it. `key` is the manifest's
 *  own spelling and is what revoke takes back, so even an entry a hand edit
 *  mangled can still be withdrawn; the typed fields are parsed from it for
 *  display and absent where it does not parse.
 */
export type RecordedDecision_Serialize = {
	scope: Scope,
	key: string,
	kind: ItemKind | null,
	name: string,
	harness: HarnessId | null,
	record: DecisionRecord_Serialize,
	state: RecordState,
};

export type ReportRouteView = {
	vstackOwned: boolean,
	repo: string | null,
	label: string | null,
	/**  Prefilled new-issue page — only when the report belongs upstream. */
	issueUrl: string | null,
};

/**
 *  One recorded review. The key it is stored under is the installation:
 *  kind, name and harness, inside the scope whose manifest holds it.
 */
export type SafetyOverride = SafetyOverride_Serialize | SafetyOverride_Deserialize;

/**
 *  One recorded review. The key it is stored under is the installation:
 *  kind, name and harness, inside the scope whose manifest holds it.
 */
export type SafetyOverride_Deserialize = {
	/**
	 *  Hash of the complete bytes that were reviewed. Empty on a record
	 *  written before decisions bound to those bytes: such a record proves
	 *  nothing about what is installed now, so it reads as stale and the
	 *  content has to be reviewed again.
	 */
	"review-hash"?: string,
	/**  The rule set that produced the findings below. */
	ruleset: number,
	/**  Fingerprints of the exact findings that were reviewed, sorted. */
	findings: string[],
	"granted-at": string,
	note?: string | null,
};

/**
 *  One recorded review. The key it is stored under is the installation:
 *  kind, name and harness, inside the scope whose manifest holds it.
 */
export type SafetyOverride_Serialize = {
	/**
	 *  Hash of the complete bytes that were reviewed. Empty on a record
	 *  written before decisions bound to those bytes: such a record proves
	 *  nothing about what is installed now, so it reads as stale and the
	 *  content has to be reviewed again.
	 */
	"review-hash": string,
	/**  The rule set that produced the findings below. */
	ruleset: number,
	/**  Fingerprints of the exact findings that were reviewed, sorted. */
	findings: string[],
	"granted-at": string,
	note?: string | null,
};

/**
 *  Every dismissal for one installation, and the content they were made
 *  against. Stored under the installation's key: kind, name and harness.
 */
export type SafetyReview = SafetyReview_Serialize | SafetyReview_Deserialize;

/**
 *  Every dismissal for one installation, and the content they were made
 *  against. Stored under the installation's key: kind, name and harness.
 */
export type SafetyReview_Deserialize = {
	"review-hash": string,
	ruleset: number,
	dismissed?: { [key in string]: Dismissal_Deserialize },
};

/**
 *  Every dismissal for one installation, and the content they were made
 *  against. Stored under the installation's key: kind, name and harness.
 */
export type SafetyReview_Serialize = {
	"review-hash": string,
	ruleset: number,
	dismissed?: { [key in string]: Dismissal_Serialize },
};

export type SafetyScore = {
	score: number,
	deductions: Deduction[],
};

export type ScanResult = {
	harnesses: DetectedHarness[],
	items: ObservedItem[],
	/**  Registered projects whose directory is gone — flagged, never dropped. */
	missingProjects: string[],
	/**  Unreadable or unparsable surfaces; truth the scan could not reach. */
	warnings: string[],
};

export type Scope = { scope: "global" } | { scope: "project"; root: string };

export type ScopeError = {
	kind: ScopeErrorKind,
	message: string,
};

/**
 *  Why a scope couldn't be audited: a kind the UI can act on (retry, remove
 *  the project, show the file) plus the plain-words message underneath it.
 */
export type ScopeErrorKind = 
/**
 *  The lock exists but isn't readable as JSON, or as this build's lock
 *  shape — damaged, not merely old.
 */
"lock-corrupt" | 
/**  The manifest or lock was written by a newer vstack than this one. */
"schema-too-new" | 
/**  The manifest parses but fails validation. */
"manifest-invalid" | "other";

export type Severity = "low" | "medium" | "high" | "critical";

/**  A rule that applies here but could not run, and why. */
export type SkippedRule = {
	rule: string,
	reason: string,
};

export type SourceDecl = SourceDecl_Serialize | SourceDecl_Deserialize;

export type SourceDecl_Deserialize = {
	repo: string | null,
	path: string | null,
	/**
	 *  Which revision of a remote to read. A full commit id is a pin: that
	 *  commit and no other, forever, and it works offline once cached. A
	 *  tag or branch tracks — every refresh re-resolves it and the new
	 *  content is previewed before anything is written. Absent tracks the
	 *  repository's default branch.
	 */
	rev: string | null,
	enabled?: boolean,
};

export type SourceDecl_Serialize = {
	repo?: string | null,
	path?: string | null,
	/**
	 *  Which revision of a remote to read. A full commit id is a pin: that
	 *  commit and no other, forever, and it works offline once cached. A
	 *  tag or branch tracks — every refresh re-resolves it and the new
	 *  content is previewed before anything is written. Absent tracks the
	 *  repository's default branch.
	 */
	rev?: string | null,
	enabled: boolean,
};

/**  Everything the Sources page shows for one declared source in one scope. */
export type SourceRow = {
	scope: Scope,
	name: string,
	reference: string,
	isRemote: boolean,
	enabled: boolean,
	/**  Cache HEAD for remotes — freshness display. */
	head: string | null,
	declaredItems: string[],
};

/**  The job an item helps with. */
export type Tag = 
/**  Reading code and saying what is wrong with it. */
"review" | 
/**  Writing, running, or reasoning about tests. */
"testing" | 
/**  Documentation, references, and explaining things in prose. */
"docs" | 
/**  Finding things out — sources, prior art, evidence. */
"research" | 
/**  Deciding what to build and in what order. */
"planning" | 
/**  Reshaping code that already works. */
"refactoring" | 
/**  Working out why something is broken. */
"debugging" | 
/**  Safety, secrets, permissions, and untrusted input. */
"security" | 
/**  Speed, memory, and the cost of running something. */
"performance" | 
/**  Version control — branches, history, worktrees, pull requests. */
"git" | 
/**  Compiling, packaging, versioning, and shipping a release. */
"release" | 
/**  Databases, schemas, migrations, and analysis. */
"data" | 
/**  Interfaces: layout, styling, design systems, accessibility. */
"ui" | 
/**  Talking to other services — APIs, webhooks, third-party tools. */
"integration" | 
/**  Driving other tools and agents, and the workflows that chain them. */
"automation";

/**
 *  Where warning starts and where installing stops. Configured in app
 *  settings rather than in a manifest: a manifest travels with the
 *  repository it describes, and a catalog that could lower the bar it is
 *  measured against is not being measured.
 */
export type Thresholds = {
	"warn-below": number,
	"block-below": number,
};

/**  One declared package's update standing. */
export type UpdateRow = {
	scope: Scope,
	kind: ItemKind,
	name: string,
	source: string,
	repo: string,
	/**  The content revision installed now, when the lock records it. */
	current: VersionRef | null,
	/**  The newest content revision the mirror knows. */
	latest: VersionRef | null,
	/**
	 *  The package's files changed between current and latest — a moved
	 *  repository that never touched this package is not an update.
	 */
	updateAvailable: boolean,
	/**  Held at a version (`rev` on the declaration) — manual updates. */
	pinned: boolean,
	/**  The user asked to stop hearing about this package's updates. */
	ignored: boolean,
	/**
	 *  The installed files were edited by hand; updating is blocked until
	 *  the edit is kept as a fork or discarded.
	 */
	blockedByLocalEdit: boolean,
	/**  This package is a local fork of a catalog item. */
	forked: boolean,
	/**  Installations of this package disagree on their source commit. */
	mixed: boolean,
};

export type Verdict = 
/**  Nothing found worth saying. */
"clean" | 
/**  Findings worth reading before installing; the install proceeds. */
"warn" | 
/**  Nothing installs until a person reviews it. */
"block";

/**  One version a row points at. */
export type VersionRef = {
	commit: string,
	/**  Release name when a tag points at the commit. */
	label: string | null,
	date: string | null,
};

/**
 *  One version of a package: a commit that changed its files, wearing any
 *  tag names that point at it.
 */
export type VersionRow = {
	/**  Full commit id. */
	id: string,
	/**  The release name, when a tag points at this commit. */
	label: string | null,
	/**  ISO-8601 committer date. */
	date: string,
	summary: string,
	/**  This is the content revision the installed package holds. */
	installed: boolean,
	newerThanInstalled: boolean,
};

/**  One side of the comparison. */
export type VersionSel = 
/**  The package's source subtree at a commit. */
{ at: "commit"; commit: string } | 
/**  What is installed on disk right now. */
{ at: "installed" };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

