// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	scanMachine: () => typedError<ScanResult, string>(__TAURI_INVOKE("scan_machine")),
	getSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_settings")),
	updateSettings: (settings: AppSettings) => typedError<AppSettings, string>(__TAURI_INVOKE("update_settings", { settings })),
	registerProject: (path: string) => typedError<AppSettings, string>(__TAURI_INVOKE("register_project", { path })),
	unregisterProject: (path: string) => typedError<AppSettings, string>(__TAURI_INVOKE("unregister_project", { path })),
	discoverProjects: (root: string) => typedError<string[], string>(__TAURI_INVOKE("discover_projects", { root })),
	/**
	 *  The full harness × kind capability matrix — the UI gates every action on
	 *  this, never on its own assumptions.
	 */
	capabilityTable: () => __TAURI_INVOKE<CapabilityRow[]>("capability_table"),
};

/* Types */
/**  App preferences and the project registry — one settings file, nothing else. */
export type AppSettings = {
	schema: number,
	projects?: string[],
	/**  Per-harness override of the global root directory, keyed by harness id. */
	"harness-roots"?: { [key in string]: string },
	appearance?: Appearance,
};

export type Appearance = "system" | "light" | "dark";

export type CapabilityRow = {
	harness: HarnessId,
	kind: ItemKind,
	caps: KindCaps,
};

/**  A harness found on this machine. */
export type DetectedHarness = {
	harness: HarnessId,
	/**  The directory whose existence marks the harness as installed. */
	root: string,
	version: string | null,
};

/**
 *  How an observed item exists on disk. Kinds that live as entries inside a
 *  shared config file (MCP servers, some hooks) are `ConfigEntry`.
 */
export type FileState = { state: "file" } | { state: "dir" } | { state: "symlink"; target: string; broken: boolean } | { state: "config-entry" };

export type HarnessId = "claude" | "codex" | "opencode" | "cursor" | "pi";

export type ItemKind = "agent" | "skill" | "hook" | "command" | "mcp-server" | "plugin" | "pi-extension";

/**
 *  What each operation supports for one harness × kind. `observe` is derived
 *  from adapter surface declarations (tested); mutation columns land with
 *  their phases and stay honest through those phases' tests.
 */
export type KindCaps = {
	observe: OpSupport,
	adopt: OpSupport,
	install: OpSupport,
	toggle: OpSupport,
	remove: OpSupport,
	refresh: OpSupport,
};

/**
 *  One item as the scanner found it — read-only truth, no interpretation of
 *  whether it is declared or managed.
 */
export type ObservedItem = {
	kind: ItemKind,
	name: string,
	harness: HarnessId,
	scope: Scope,
	/**  Path of the artifact, or of the config file that contains the entry. */
	path: string,
	fileState: FileState,
	/**
	 *  Observable enabled/disabled state; `None` when the harness has no
	 *  observable toggle for this kind.
	 */
	enabled: boolean | null,
	/**  Best-effort provenance: git origin URL of the content's real location. */
	origin: string | null,
	description: string | null,
};

export type OpSupport = {
	project: boolean,
	global: boolean,
};

export type ScanResult = {
	harnesses: DetectedHarness[],
	items: ObservedItem[],
	/**  Registered projects whose directory is gone — flagged, never dropped. */
	missingProjects: string[],
	/**  Unreadable or unparsable surfaces; truth the scan could not reach. */
	warnings: string[],
};

export type Scope = { scope: "global" } | { scope: "project"; root: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

